services:
  - docker
language: java
jdk:
  - openjdk8
os: linux
sudo: false
script: mvn clean verify -P docker

before_install:
  - mkdir logs
  - export PATH=$JAVA_HOME/bin:$PATH

after_success:
  - bash <(curl -s https://codecov.io/bash)