# Cyclone configuration file

server:
  applicationConnectors:
    - type: http
      port: 8080

cluster:
  nodeIdentifierProvider:
    type: org.cempaka.cyclone.services.StaticNodeIdentifierProvider
    # Node id's should be unique across all nodes in cluster.
    parameters:
      nodeId: localhost
  # Controls when node will be marked as dead. Values are in seconds.
#  heartbeatInterval: 10
#  heartbeatManagedAwaitInterval: 60

storage:
  parcelRepository:
    type: org.cempaka.cyclone.storage.repositories.JdbiParcelRepository

workers:
  # Number of test runners.
  workersNumber: 1
  # Path to the guava jar. Used for gathering parcels metadata.
  guavaPath: cyclone-daemon/target/dependency/guava.jar
  # Path to store logs from load tests.
  logsPath: logs/

auth:
  # Type of the authentication mechanism. Allowed values are: NONE, BASIC, HEADER.
  type: NONE
#  properties: {}

# JDBI configuration see: https://www.dropwizard.io/en/stable/manual/jdbi.html#configuration
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: cyclone
  url: jdbc:postgresql://localhost/postgres
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

# Dropwizard logging configuration
logging:
  level: INFO
  loggers:
    org.cempaka: DEBUG
