version: '3.7'

services:
  postgres:
    image: postgres:15.5-alpine
    environment:
      POSTGRES_USER: cyclone
      POSTGRES_PASSWORD: cyclone
  cyclone:
    image: cempaka/cyclone:0.3-SNAPSHOT
    depends_on:
      - postgres
    ports:
      - 8000
