version: '3.7'

services:
  postgres:
    image: postgres:9.5.16-alpine
    environment:
      POSTGRES_USER: cyclone
      POSTGRES_PASSWORD: cyclone
  cyclone:
    image: cempaka/cyclone:0.2-SNAPSHOT
    depends_on:
      - postgres
    ports:
      - 8000
